### ISSUE TITLE
Exception when the new schema is composed

### ISSUE THREAD

**Issue by quen2404** [quen2404/openapi-diff#17]
If the schema change from standard schema to composed schema (anyOf, oneOf, allOf). an exception is raised: 
```
Exception in thread "main" java.lang.ClassCastException: io.swagger.v3.oas.models.media.Schema cannot be cast to io.swagger.v3.oas.models.media.ComposedSchema
	at com.qdesrame.openapi.diff.compare.schemadiffresult.ComposedSchemaDiffResult.diff(ComposedSchemaDiffResult.java:32)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:86)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:16)
	at com.qdesrame.openapi.diff.compare.ReferenceDiffCache.cachedDiff(ReferenceDiffCache.java:39)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.diff(SchemaDiff.java:62)
	at com.qdesrame.openapi.diff.compare.ContentDiff.diff(ContentDiff.java:38)
	at com.qdesrame.openapi.diff.compare.RequestBodyDiff.computeDiff(RequestBodyDiff.java:56)
	at com.qdesrame.openapi.diff.compare.RequestBodyDiff.computeDiff(RequestBodyDiff.java:15)
	at com.qdesrame.openapi.diff.compare.ReferenceDiffCache.cachedDiff(ReferenceDiffCache.java:39)
	at com.qdesrame.openapi.diff.compare.RequestBodyDiff.diff(RequestBodyDiff.java:24)
	at com.qdesrame.openapi.diff.compare.OperationDiff.diff(OperationDiff.java:26)
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:160)
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:93)
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:59)
	at com.qdesrame.openapi.diff.Main.main(Main.java:91)
```

**Comment by adarshsharma** [comment]
raised a PR https://github.com/quen2404/openapi-diff/pull/19

**Comment by quen2404** [comment]
Thank you adarsh ! 👍
