### ISSUE TITLE
StackOverflowError with recursion

### ISSUE THREAD

**Issue by jmini** [quen2404/openapi-diff#25]
_First of all, thank you for this work! I am evaluating if we will use it to detect breaking changes between two versions of our API and I think we will._

---

I have run your tool against the items provided in the test suite of this project: [Azure/openapi-diff](https://github.com/Azure/openapi-diff/)
(with some modifications, I can provide more details on my approach if you are interested)

By doing this, I have noticed that the recursion case is not properly handled by this tool.

With this spec as input:

```
openapi: 3.0.1
info:
  title: recursive test
  version: '1.0'
servers:
  - url: 'http://localhost:8000/'
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/B'
components:
  schemas:
    B:
      type: object
      properties:
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/B'
```
You get a Stacktrace like this:

```
Exception in thread "main" java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:245)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:611)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at java.util.Formatter.getZero(Formatter.java:2283)
	at java.util.Formatter.<init>(Formatter.java:1892)
	at java.util.Formatter.<init>(Formatter.java:1914)
	at java.lang.String.format(String.java:2940)
	at com.qdesrame.openapi.diff.utils.RefPointer.getBaseRefForType(RefPointer.java:56)
	at com.qdesrame.openapi.diff.utils.RefPointer.getRefName(RefPointer.java:67)
	at com.qdesrame.openapi.diff.utils.RefPointer.resolveRef(RefPointer.java:20)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:75)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:16)
	at com.qdesrame.openapi.diff.compare.ReferenceDiffCache.cachedDiff(ReferenceDiffCache.java:39)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.diff(SchemaDiff.java:62)
	at com.qdesrame.openapi.diff.compare.schemadiffresult.ArraySchemaDiffResult.diff(ArraySchemaDiffResult.java:23)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:90)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:16)
	at com.qdesrame.openapi.diff.compare.ReferenceDiffCache.cachedDiff(ReferenceDiffCache.java:39)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.diff(SchemaDiff.java:62)
	at com.qdesrame.openapi.diff.compare.schemadiffresult.SchemaDiffResult.diff(SchemaDiffResult.java:53)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:90)
	at com.qdesrame.openapi.diff.compare.SchemaDiff.computeDiff(SchemaDiff.java:16)
```

I think that projects like [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators/) have some mechanisms to handle those cases.

Something similar should be implemented here.

**Comment by quen2404** [comment]
Thank you @jmini for this return. I was not thinking that could happen. 
I looked your link to the  [Azure/openapi-diff](https://github.com/Azure/openapi-diff) project and I saw their rules part. It is a good idea to define explicitly how the behavior works. I will try to do the same work in my project.
Yes, I'm interested by your approach ! It will be cool if i could reuse the test suite of Azure to enhance this project.

Now, about the bug, I will take a look to [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators/) project and other Java projects that could help me resolve this kind of circular linking.

**Comment by jmini** [comment]
> I looked your link to the Azure/openapi-diff project and I saw their rules part. It is a good idea to define explicitly how the behavior works. I will try to do the same work in my project.

=> Lets discuss this in #26 

---

> I will take a look to swagger-codegen-generators project and other Java projects that could help me resolve this kind of circular linking.

Maybe a start (I did not looked precisely): [ExampleGeneratorTest.recursiveModelsTest()](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/modules/swagger-codegen/src/test/java/io/swagger/codegen/ExampleGeneratorTest.java#L25).

**Comment by adarshsharma** [comment]
@jmini you have mentioned the sample input for this issue to be reproduced. Is it both old and new spec or you were using any different new spec?

**Comment by jmini** [comment]
I have tested it with the same spec as input for both old and new input (diff is expected to represent an empty diff that case).

**Comment by adarshsharma** [comment]
Sure. I'll take a look at it.

**Comment by adarshsharma** [comment]
Raised a PR https://github.com/quen2404/openapi-diff/pull/27 for this issue

**Comment by quen2404** [comment]
Thanks @adarshsharma for this fix ! 👍
