### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by hellboy81** [quen2404/openapi-diff#63]
```java
java -jar "openapi-diff-1.2.0.jar"
java : no main manifest attribute, in openapi-diff-1.2.0.jar
At line:1 char:1
+ java -jar "openapi-diff-1.2.0.jar" --help
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (no main manifes...-diff-1.2.0.jar:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

```java
java -cp "openapi-diff-1.2.0.jar" com.qdesrame.openapi.diff.Main 
java : java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
At line:1 char:1
+ java -cp "openapi-diff-1.2.0.jar" com.qdesrame.openapi.diff.Main
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (java.lang.NoCla.../ParseException:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.privateGetMethodRecursive(Unknown Source)
    at java.lang.Class.getMethod0(Unknown Source)
    at java.lang.Class.getMethod(Unknown Source)
    at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
    at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
````

**Comment by quen2404** [comment]
Hi, i think you are trying to run the wrong jar. You try to run the library jar which is not executable. Try with the .jar which ends with `with-dependencies`
