### ISSUE TITLE
IllegalArgumentException: "Invalid ref...", while having attribute with the same name in different 'components' sections

### ISSUE THREAD

**Issue by NikitaMarushkai** [quen2404/openapi-diff#68]
Hello! Thanks for the nice util, but I faced one problem that doesn't make me possible to use this. I have the following API definition sections:

```
components:
  parameters:
    gender:
      name: gender
      description: Customer gender
      in: query
      schema:
        $ref: '#/components/schemas/Gender'
  schemas:
    Gender:
      type: string
      enum:
      - MALE
      - FEMALE
      - NOT_SPECIFIED
```
And the comparision of versions fails with the following exception:
```
java.lang.IllegalArgumentException: Invalid ref: #/components/schemas/Gender
	at com.qdesrame.openapi.diff.utils.RefPointer.getRefName(RefPointer.java:69) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.utils.RefPointer.resolveRef(RefPointer.java:20) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.ParametersDiff.diff(ParametersDiff.java:46) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.OperationDiff.diff(OperationDiff.java:34) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.PathDiff.diff(PathDiff.java:31) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.PathsDiff.lambda$diff$2(PathsDiff.java:53) ~[openapi-diff-1.2.0.jar:na]
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559) ~[na:1.8.0_191]
	at com.qdesrame.openapi.diff.compare.PathsDiff.diff(PathsDiff.java:36) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:92) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:66) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.OpenApiCompare.fromSpecifications(OpenApiCompare.java:99) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.OpenApiCompare.fromContents(OpenApiCompare.java:42) ~[openapi-diff-1.2.0.jar:na]
	at com.qdesrame.openapi.diff.OpenApiCompare.fromContents(OpenApiCompare.java:30) ~[openapi-diff-1.2.0.jar:na]
```
I suppose that this happening because of my `parameters` and `schemas` sections have attributes with the same name.

**Comment by NikitaMarushkai** [comment]
Sorry, I guess this was my mistake, that's not about having different components in different sections, that error was because of me referencing `schemas` component from /get parameters section instead of referencing the `parameters`

**Comment by quen2404** [comment]
Hi @NikitaMarushkai, thanks for the issue. It seems that your behavior is still a bug, could you give me a complete example ?

**Comment by quen2404** [comment]
Also, you should try with the version `2.0.0-SNAPSHOT`. A lot of bugs are fixed :smile:

**Comment by NikitaMarushkai** [comment]
> Also, you should try with the version `2.0.0-SNAPSHOT`. A lot of bugs are fixed

Hi there! Is this version have a build, deployed somewhere or should I build a jar by myself?

**Comment by NikitaMarushkai** [comment]
In details, this happened due to the following spec: 
```
some/method:
  get:
    parameters:
      - $ref: '/components/schemas/Gender'
```
The validation of this schema by your tool fails with the exception, which I mentioned above.
But if i change this to:
```
some/method:
  get:
    parameters:
      - $ref: '/components/parameters/Gender'
```
It passes validation fine, but I'm not sure that this should be treated as a bug, because as it is showed up, my swagger can't render this field in the web view as well.

**Comment by quen2404** [comment]
Ok, i understand ! Thank you ! :+1:
So, you're right, not a bug !
