### ISSUE TITLE
NPE for APIResponseDiff

### ISSUE THREAD

**Issue by sah4ez** [quen2404/openapi-diff#71]
Thank for you excellent tool!
When I tried compare two my swagger files, I got an error:
```
java.lang.NullPointerException
	at com.qdesrame.openapi.diff.compare.ApiResponseDiff.diff(ApiResponseDiff.java:41)
	at com.qdesrame.openapi.diff.compare.OperationDiff.diff(OperationDiff.java:59)
	at com.qdesrame.openapi.diff.compare.PathDiff.diff(PathDiff.java:35)
	at com.qdesrame.openapi.diff.compare.PathsDiff.lambda$diff$2(PathsDiff.java:69)
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
	at com.qdesrame.openapi.diff.compare.PathsDiff.diff(PathsDiff.java:40)
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:97)
	at com.qdesrame.openapi.diff.compare.OpenApiDiff.compare(OpenApiDiff.java:68)
	at com.qdesrame.openapi.diff.OpenApiCompare.fromSpecifications(OpenApiCompare.java:101)
	at com.qdesrame.openapi.diff.OpenApiCompare.fromLocations(OpenApiCompare.java:90)
	at com.qdesrame.openapi.diff.OpenApiCompare.fromLocations(OpenApiCompare.java:77)
	at com.qdesrame.openapi.diff.Main.main(Main.java:141)
```

```
openApiDiff
        .getExtensionsDiff()
        .diff(left.getExtensions(), right.getExtensions(), context)
        .ifPresent(changedApiResponse::setExtensions);
```
I see in debugger and found that in method `diff` variable `left` equal to `null`.

**Comment by sah4ez** [comment]
I had a typos in my swagger file, in old version. I missed `s` in `responses` for the one path. After fixing all work good, but I didn't see human readable notification about typos...

**Comment by quen2404** [comment]
Hum, you should probably use another tool to check that your swagger is compliant to specification

**Comment by KuzinGit** [comment]
Think it is helpful for cases when RequsetBody is added or removed from request, In this case NPE occurs, but schema is valid.
